<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-TDN5H4E" failures="1" tests="5" name="personalloan" time="0.158" errors="0" timestamp="2023-11-24T16:12:30 IST">
  <testcase classname="test.day1" name="secondtest" time="0.022">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.secondtest(day1.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- secondtest -->
  <testcase classname="test.day2" name="thirdtest" time="0.004"/>
  <testcase classname="test.day4" name="homeloanapilogin" time="0.004"/>
  <testcase classname="test.day4" name="homeloanmobilelogin" time="0.006"/>
  <testcase classname="test.day4" name="homeloanweblogin" time="0.002"/>
  <testcase classname="test.day1" name="demo" time="0.0">
    <ignored/>
  </testcase> <!-- demo -->
  <testcase classname="test.day1" name="thirdtest" time="0.0">
    <ignored/>
  </testcase> <!-- thirdtest -->
</testsuite> <!-- personalloan -->
